version: 2.1

# -------------------------
#        DEFAULTS
# -------------------------
defaults: &defaults
  working_directory: ~/react-responsive-pinch-zoom-pan

# -------------------------
#        EXECUTORS
# -------------------------
executors:
  nodejs:
    <<: *defaults
    docker:
      - image: circleci/node:latest

# -------------------------
#        ORBS
# -------------------------
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@0.1.18

# -------------------------
#          JOBS
# -------------------------
jobs:
  build:
    parameters:
      executor:
        type: executor
        default: nodejs
      checkout_type:
        type: string
        default: node
    executor: << parameters.executor >>
    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run: npm run prepublishOnly

      - persist_to_workspace:
          root: ~/react-responsive-pinch-zoom-pan
          paths:
            - dist
            - node_modules

      - slack/status:
          fail_only: true
          channel: build-react-responsive-pinch-zoom-pan
          success_message: ':tada: build job has succeeded!'
          failure_message: ':red_circle: build job has failed!'

  deploy:
    parameters:
      executor:
        type: executor
        default: nodejs
      checkout_type:
        type: string
        default: node
    executor: << parameters.executor >>
    steps:
      - run:
          name: Generate .npmrc
          command: |
            echo "//npm.pkg.github.com/:_authToken="$GITHUB_TOKEN > ~/.npmrc

      - checkout

      - attach_workspace:
          at: ~/react-responsive-pinch-zoom-pan

      - run:
          name: Set version
          command: |
            jq --arg version "$CIRCLE_TAG" '.version = $version' package.json > package-updated.json
            mv package-updated.json package.json

      - run: npm publish

      - slack/status:
          fail_only: true
          channel: build-react-responsive-pinch-zoom-pan
          success_message: ':tada: deploy job has succeeded!'
          failure_message: ':red_circle: deploy job has failed!'

  notify:
    parameters:
      executor:
        type: executor
        default: nodejs
      checkout_type:
        type: string
        default: node
    executor: << parameters.executor >>
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - slack/notify:
          channel: build-react-responsive-pinch-zoom-pan
          color: "#1cbf43"
          message: ":tada: react-responsive-pinch-zoom-pan version $CIRCLE_TAG has been deployed!"

workflows:
  version: 2
  packaged:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          context: github
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - notify:
          requires:
            - deploy
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
